name: CI MAIN

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Node.js + cache PNPM
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run ci
      run: pnpm run full-ci